name = "winkai"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[pages_build_output]]
directory = "dist"

[env.production]
name = "winkai-production"

[env.preview]
name = "winkai-preview"
